{{- if or .Values.k8up.tolerations.key .Values.affinity.key }}
apiVersion: k8up.io/v1
kind: PodConfig
metadata:
  name: backups-podconfig
spec:
  template:
    spec:
      {{- with .Values.k8up.securityContext }}
      securityContext:
        runAsUser: {{ .runAsUser }}
      {{- end }}
      tolerations:
        - key: {{ .Values.k8up.tolerations.key }}
          operator: {{ .Values.k8up.tolerations.operator }}
          value: {{ .Values.k8up.tolerations.value }}
          effect: {{ .Values.k8up.tolerations.effect }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: {{ .Values.k8up.affinity.key }}
                  operator: In
                  values:
                    - {{ .Values.k8up.affinity.value }}
      containers:
        - name: test
          env:
          - name: GHOST
            value: 'true'
{{- end }}
