---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
#    nginx.ingress.kubernetes.io/auth-signin: "https://vouch.cloudydev.net/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err"
#    nginx.ingress.kubernetes.io/auth-url: https://***REMOVED***/validate
#    nginx.ingress.kubernetes.io/auth-response-headers: X-Vouch-User
#    nginx.ingress.kubernetes.io/auth-snippet: |
#      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
#      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
#      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;   
spec:
  tls:
    - hosts:
      - iam.vleermuis.tech
      secretName: keycloak-tls
  rules:
  - host: iam.vleermuis.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080
