# Use external secrets. Set to bitwarden to use this chart. other providers may be supported in the future
provider: ""

adminCredentialsBitwardenID: ""
pgsqlCredentialsBitwardenID: ""
redisCredentialsBitwardenID: ""
mastodonSecretsBitwardenID: ""
smtpCredentialsBitwardenID: ""

# -- if set to seaweedfs we deploy a policy secret. can also be minio
s3_provider: "seaweedfs"

# -- existing kubernetes secret with s3 admin credentials
s3AdminCredentialsBitwardenID: ""
# -- existing kubernetes secret with s3 mastodon credentials
s3MastodonCredentialsBitwardenID: ""
# -- existing kubernetes secret with s3 postgres credentials
s3PostgresCredentialsBitwardenID: ""

# -- existing kubernetes secret with s3 credentials for the remote backups
s3BackupCredentialsBitwardenID: ""
