## if this is not set to "bitwarden", we will not actually deploy any templates
# other providers may be supported in the future
provider: "true"

# the item ID of the Bitwarden admin credentials
bitwardenAdminCredentialsID: ""
