{{- if eq .Values.provider "bitwarden" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netmaker-oauth-config
spec:
  target:
    # Name for the secret to be created on the cluster
    name: netmaker-oauth-config
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        CLIENT_ID: |-
          {{ `{{ .username }}` }}
        CLIENT_SECRET: |-
          {{ `{{ .password }}` }}
        OIDC_ISSUER: |-
          {{ `{{ .issuer }}` }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: {{ .Values.netmakerOauthConfigBitwardenID }}
        property: username

    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: {{ .Values.netmakerOauthConfigBitwardenID }}
        property: password

    - secretKey: issuer
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: {{ .Values.netmakerOauthConfigBitwardenID }}
        property: issuer
{{- end }}
