# Helm Values:
# https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator/values.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgoperator
spec:
  destination:
    namespace: postgres-operator
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://opensource.zalando.com/postgres-operator/charts/postgres-operator'
    targetRevision: 1.10.0
    chart: postgres-operator
    helm:
      skipCrds: true
      values: |
        configLoadBalancer:
          db_hosted_zone: db.social-media-for-dogs.com
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
