# -- if this is not set to "bitwarden", we will not actually deploy any templates
# we may support other secret providers in the future
provider: ""

# -- zitadel OIDC Credentials
oidcCredentialsBitwardenID: ""
